### ISSUE TITLE
Any way to change touchscreen controller to act as a sideways controller?

### ISSUE THREAD

**Issue by mak448a** [OatmealDome/dolphin-ios#105]
Is there a way to change the touchscreen controller to act as a sideways controller for use in games like Super Paper Mario?

**Comment by Linkdash2019** [comment]
Yes there is! Go to Settings -> Controllers -> Wii Remote # -> Configure -> Options 
There should be an option called Sideways Wii Remote. Toggle it on.

**Comment by mak448a** [comment]
Thank you!
