### ISSUE TITLE
Fastmem Region Map Memory Error

### ISSUE THREAD

**Issue by brand175** [OatmealDome/dolphin-ios#110]
iOS 17.1.1.

Metroid Prime 1 or any other game

Only happens on my iPhone 15 Pro Max
![IMG_1962](https://github.com/OatmealDome/dolphin-ios/assets/20964160/0d4bfa35-cb18-44ae-9319-fadddcb6c763)

Disabling fastmem fixes this.
Using current build on this repo

**Comment by brand175** [comment]
Can confirm that 4.0.0b5 runs Fastmem but have no idea if it's soft-fastmem (Or true fastmem)

**Comment by brand175** [comment]
Heres the error

![IMG_2265](https://github.com/OatmealDome/dolphin-ios/assets/20964160/95806d33-fb8d-450e-95fb-b0dc785c4abe)

**Comment by OatmealDome** [comment]
Fixed in b7.
