### ISSUE TITLE
DolphinOS crashes when opening a game

### ISSUE THREAD

**Issue by ismayel21** [OatmealDome/dolphin-ios#114]
Managed to make jit work on iphone 15 plus but when entering to a game the app crashes and I need to enable jit all over again, the "waiting for JIT" screen disappears and the game screen appear but the game doesn't load and closes the app

**Comment by Spidy123222** [comment]
> Managed to make jit work on iphone 15 plus but when entering to a game the app crashes and I need to enable jit all over again, the "waiting for JIT" screen disappears and the game screen appear but the game doesn't load and closes the app 
> 
> 
Use dolphinios 4.0.0b5 https://github.com/OatmealDome/dolphin-ios/releases/tag/v4.0.0b5

**Comment by ismayel21** [comment]
> > Managed to make jit work on iphone 15 plus but when entering to a game the app crashes and I need to enable jit all over again, the "waiting for JIT" screen disappears and the game screen appear but the game doesn't load and closes the app
> 
> Use dolphinios 4.0.0b5 https://github.com/OatmealDome/dolphin-ios/releases/tag/v4.0.0b5

How do I install it? I'm sorry, I am really new at this

**Comment by AbnormalPoof** [comment]
Same way you installed 3.2.1 (Don’t grab the .tipa or .deb file)

**Comment by ismayel21** [comment]
I installed it with AltStore in my iPhone, and I can't find how to install the 4.0.0b5 version with AltStore

**Comment by mygizli04** [comment]
I had the same issue and updating to 4.0.0b5 fixed it

**Comment by Simonx22** [comment]
As mentioned by the others, please use v4.0.0. It's available here: https://dolphinios.oatmealdome.me/beta
