### ISSUE TITLE
Error when running the game

### ISSUE THREAD

**Issue by ggyf711** [OatmealDome/dolphin-ios#115]
![image](https://github.com/OatmealDome/dolphin-ios/assets/54673222/735ca358-f56e-4327-b505-12e39bdf895e)iphone11 ios16.6.1 4.0.0b6（13）

**Comment by Simonx22** [comment]
This issue should be fixed with [4.0.0b7](https://github.com/OatmealDome/dolphin-ios/releases/tag/v4.0.0b7). Please try again with that version.

**Comment by ggyf711** [comment]
4.0.0b7(15) Thank you very much for running the game perfectly
