### ISSUE TITLE
Can't add games?

### ISSUE THREAD

**Issue by Igloocooler52** [OatmealDome/dolphin-ios#118]
The files are greyed out, theyre "On My iPhone" and downloaded, so im REALLY confused
![IMG_DBA22E43E599-1](https://github.com/OatmealDome/dolphin-ios/assets/98135234/830460d5-d117-4376-8f87-ed1fc1a0799a) (Hope the image link isnt broken)

**Comment by Simonx22** [comment]
We do not support privacy. Dump your own games.
