### ISSUE TITLE
App Store release

### ISSUE THREAD

**Issue by skythomp16** [OatmealDome/dolphin-ios#135]
Now that Apple allows emulators on the App Store and the Delta emulator has made the move for several Nintendo systems, is there any current plans to release Dolphin iOS on the App Store too?

**Comment by OatmealDome** [comment]
Not possible. DolphiniOS requires JIT support for fast CPU emulation, and Apple is still heavily restricting access to this feature.

**Comment by skythomp16** [comment]
Bummer... Maybe they'll open that up with iOS 18 but I won't hold my breath
