### ISSUE TITLE
Add Dolphin iOS to Apple App Store

### ISSUE THREAD

**Issue by Nbelles** [OatmealDome/dolphin-ios#138]
Now that Apple is allowing game emulators on the App Store, can we expect Dolphin iOS to make it to the Apple App Store sometime soon? 

Apple recently updated its App Store guidelines to allow game emulators ([link](https://www.macrumors.com/2024/04/05/app-store-guidelines-emulators-music-app-links/)) and now the Delta game emulator has made it’s debut as well ([link](https://faq.deltaemulator.com/)). It would be really awesome to see the Dolphin iOS emulator to make it’s way to the App Store as well.

Thanks!

**Comment by OatmealDome** [comment]
Unfortunately, it isn't possible at this time. Please refer to this blog post I made talking about it: https://oatmealdome.me/blog/why-dolphin-isnt-coming-to-the-app-store/
