### ISSUE TITLE
Is necessary activate JIT every time i open Dolphinios?

### ISSUE THREAD

**Issue by lokize** [OatmealDome/dolphin-ios#143]
Every time i open Dolphinios i need activate JIT? Is there any way to make JIT permanently ?

![image](https://github.com/OatmealDome/dolphin-ios/assets/19701630/3d521abc-b546-4c1e-92a2-3baadb3228d0)

**Comment by OatmealDome** [comment]
> Is there any way to make JIT permanently ?

No. This is an Apple restriction.

**Comment by lokize** [comment]
> > Is there any way to make JIT permanently ?
> 
> 
> 
> No. This is an Apple restriction.

Its boring when i away from home, i cant play without Connect in my pc And make JIT...
