### ISSUE TITLE
iOS 18 support?

### ISSUE THREAD

**Issue by Samuel525432** [OatmealDome/dolphin-ios#154]
I was thinking does DolphiniOS supports iOS 18?
What I mean is does Dolphin iOS support iOS 18
iPhone 14 Pro Max (my main device)
iOS 18b3 btw

**Comment by OatmealDome** [comment]
DolphiniOS itself should be compatible.

However, the JIT enablers may not be compatible. Ask the developer of the JIT enabler you are using.

**Comment by chunchundeniuma** [comment]
found an usefull app ，named "livecontainer", it can enable JIT without PC.

**Comment by Samuel525432** [comment]
> found an usefull app ，named "livecontainer", it can enable JIT without PC.

Well technically you need StikDebug to enable JIT
