### ISSUE TITLE
Saying game already exist but not showing game

### ISSUE THREAD

**Issue by Ronadloooooo** [OatmealDome/dolphin-ios#155]
I downloaded an iso and I moved it to the software file like I have to but when I open dolphin it’s not there I even try pressing on the plus and adding but it says it’s already there pls help
![IMG_0859](https://github.com/user-attachments/assets/5695ff90-ee20-4e41-9041-1f41f88605fc) 
![IMG_0861](https://github.com/user-attachments/assets/c7a5006c-f7c1-4750-bfb5-3c131828b06b)
I dont know if I’m doing something wrong

**Comment by OatmealDome** [comment]
Downloading games is piracy. We don't support piracy.
