### ISSUE TITLE
Softmmu should be displayed

### ISSUE THREAD

**Issue by Spidy123222** [OatmealDome/dolphin-ios#29]
Softmmu should be displayed in debug menu and or have a toggle in debug menu in settings same for fastmem. ![image](https://user-images.githubusercontent.com/64176728/212658193-f4efffc6-bee0-4e3c-a1ca-2a9c32bbb687.png)

**Comment by OatmealDome** [comment]
SoftMMU has no toggle, even in official Dolphin. Since I don't want to deviate too much from official (to make keeping up to date with it easier), I won't be adding one.

**Comment by OatmealDome** [comment]
I will be adding one for fastmem, though (on = fastmem, off = softmmu). Maybe this is what you wanted?
