### ISSUE TITLE
Crash in JITMemoryTracker

### ISSUE THREAD

**Issue by OatmealDome** [OatmealDome/dolphin-ios#33]
Crash report from brand:

```
Thread 17 name:  CPU thread
Thread 17 Crashed:
0   libdolphin.dylib              	       0x105153e54 Common::JITMemoryTracker::JITRegionWriteEnableExecuteDisable(void*) + 16
1   libdolphin.dylib              	       0x105153e50 Common::JITMemoryTracker::JITRegionWriteEnableExecuteDisable(void*) + 12
```

Possibly threading issue (simultaneous access)? Probably should include locks in every call that modifies the map.

**Comment by OatmealDome** [comment]
Mitigations added for simultaneous access. Let's see if this appears again in the next beta.

**Comment by Simonx22** [comment]
Does this issue still occur?

**Comment by OatmealDome** [comment]
Going to assume this issue is fixed. If I see it reappear, I'll reopen this issue.
