### ISSUE TITLE
[BUG] Menu bar always visible

### ISSUE THREAD

**Issue by HStephens05** [OatmealDome/dolphin-ios#39]
On notched devices, the menu bar that lets you swipe to go home is always visible. This takes up screen real estate and causes the emulation to be smaller than it should.

![IMG_2727](https://user-images.githubusercontent.com/78606100/213881800-32609b6f-9093-4c2e-8585-85a5e1090f5f.PNG)

**Comment by OatmealDome** [comment]
Fixed.
