### ISSUE TITLE
[Feature Request] RetroAchievements integration 

### ISSUE THREAD

**Issue by MichaelGDev48** [OatmealDome/dolphin-ios#53]
It would be awesome if at some point we get RetroAchievements integration into dolphin-ios. I love collecting achievements and it would add more value to the emulator :)

**Comment by OatmealDome** [comment]
This request is more suited for the official version of Dolphin, since this would be implemented in the Dolphin core. They are aware of the interest of RetroAchivements: https://bugs.dolphin-emu.org/issues/12896.

**Comment by MichaelGDev48** [comment]
Fair enough

**Comment by olipra** [comment]
RetroAchievements got implemented in the Dolphin core! :)
Does this mean an upcoming Dolphin-iOS update with RetroAchievements integration is coming?

Edit: **Wii** RetroAchievement specifically
