### ISSUE TITLE
JIT Failure

### ISSUE THREAD

**Issue by Tracker-Friendly** [OatmealDome/dolphin-ios#66]
DolphiniOS could not acquire JIT from csdbgd or jailbreakd

Unable to open port

Using palera1n (procurus / checkm8 based) and i have got csdbgd installed
Tested on beta and normal

**Comment by OatmealDome** [comment]
Thanks for your report. We are no longer accepting reports for 3.2.1 and below. Please reopen if this issue report it still happens on a 4.0.0 beta version.
