### ISSUE TITLE
How do I add gecko code to a game?

### ISSUE THREAD

**Issue by Jadon67** [OatmealDome/dolphin-ios#70]

**Comment by Jadon67** [comment]
When I try tap and hold on a game, it does nothing…..

**Comment by Simonx22** [comment]
The feature is currently not implemented in the new version. You should be able to manually change the configuration files for now though. 

Anyway, closing as duplicate since we have https://github.com/OatmealDome/dolphin-ios/issues/20 to add it back.

**Comment by Jadon67** [comment]
Thanks
