### ISSUE TITLE
Connect dolphin bar for dolphin ios

### ISSUE THREAD

**Issue by salssito** [OatmealDome/dolphin-ios#75]
Need to connect dolphin bar for dolphin ios like they do in android to connect wii controlers for playing wii games

**Comment by Spidy123222** [comment]
> Need to connect dolphin bar for dolphin ios like they do in android to connect wii controlers for playing wii games

The Nintendo Wii bar doesn't communicate anything as it uses IR led's to help the wiimote know you are pointing to tv and uses it for pointing the cursor and stuff via the ir sensor at top of the controller. Connecting a wiimote to iOS is currently impossible (likely with jailbreaks but doesn't exist yet) with current restrictions.

**Comment by Simonx22** [comment]
I'm going to close this issue because there's really nothing to do that's within the scope of this project
