### ISSUE TITLE
Add dolphin bar may flash wii controler Like for android 

### ISSUE THREAD

**Issue by salssito** [OatmealDome/dolphin-ios#78]
![IMG_3056](https://user-images.githubusercontent.com/105934545/230729654-771cc60c-bbdc-4060-9a7c-6b840560aac8.png)
![IMG_3057](https://user-images.githubusercontent.com/105934545/230729659-ad328c61-08c8-483c-b6cd-527270d8a61f.png)

**Comment by salssito** [comment]
![image](https://user-images.githubusercontent.com/105934545/230729941-4090fced-5adb-44bd-a5e2-cdb7569d9635.jpg)


Cannot select the wii mote physique alghouth the dolphin bar is connected

**Comment by OatmealDome** [comment]
iOS only supports a limited selection of USB devices. It does not support connecting a DolphinBar.

There is no way to connect a real Wii Remote to an iOS device.
