### ISSUE TITLE
JIT not enabled on IOS 15 jailbroken

### ISSUE THREAD

**Issue by snkdonkey** [OatmealDome/dolphin-ios#79]
I am jailbroken on ios 15 and i went to use dolphin but it says it cannot detect jit from jailbreakd or csdbgd. is there anyway i could enable jit?

**Comment by OatmealDome** [comment]
jailbreakd and csdbgd are no longer used in the new version of the app. Try the latest beta release here: https://github.com/OatmealDome/dolphin-ios/releases/tag/v4.0.0b5
