### ISSUE TITLE
‘“DiOS (Beta)” is no longer available’ notification when I try to launch the app.

### ISSUE THREAD

**Issue by Maxiev209913** [OatmealDome/dolphin-ios#80]
Whenever I try to open the app, a notification pops up that reads: ‘“DiOS (Beta)” is no longer available’. My device is not jailbroken.

**Comment by HStephens05** [comment]
This is normal. Apple places restrictions on nonjailbroken devices and forces users to reinstall their sideloaded apps after 7 days.
