### ISSUE TITLE
DDS textures do not load.

### ISSUE THREAD

**Issue by sysconf16** [OatmealDome/dolphin-ios#85]
As per title. PNG texture packs work perfectly, but create stutter in gameplay.
DDS texture packs do not load at all, but would be useful to use as they would eliminate the stuttering that PNG texture packs introduce.

Currently using the latest beta build as of the writing of this.

**Comment by OatmealDome** [comment]
DDS textures will be supported in a future version. However, I believe it will require a device running iOS 16.4+ with an M1 chip inside.

**Comment by OatmealDome** [comment]
Added in 4.0.0b7, thanks to TellowKrinkle. Requires an M1 chip.
